### ISSUE TITLE
A more detailed readme or explanation of  the parameters in blob.h would be appreciated.

### ISSUE THREAD

**Issue by namemzy** [hjptriplebee/car_detection_counting#1]
Thank you for you kind open source！
When I test my video with your project, I am wondering how to reset these massive parameters in test.cpp and blob.h.  Which made a chaos visualization result and wrong counting number in the code test. Could you give me a detailed parameter configure list on how to reset it when testing another video. updating the readme file will be better and be appreciated.

![image](https://user-images.githubusercontent.com/33368578/59479164-8f2b7180-8e8e-11e9-8ba4-8277092bed87.png)

**Comment by hjptriplebee** [comment]
Readme has been updated

**Comment by namemzy** [comment]
I have understood the meaning of these parameters and known how to modify them. Thank you for your kindly help!
